# Advanced Machine Learning with Python
# Dr. Ali Dag
# Assignment 2

## There are 10 questions and each question is worth 0.5 pt, totaling 5 points. 
## Due date : Feb 19 (Friay), 2021 at 11:59 pm

## Name the file “Name_Assignmnet2.ipynb” <br />

If the question is not clear for you:<br />
    - Use your judgement
    - State your assumptions (what do you understand)
    - Solve the problem
    
Good luck!

## Question 1

** Create a basic function that returns True if the word 'cat' is contained in the input string. Don't worry about edge cases like a punctuation being attached to the word cat, but do account for capitalization (CAT, cat, Cat, ....regarless of the case) **


-  Hint : Use split function

In [11]:
str_name = str(input())
str_name = str_name.lower()
    
def func():
    if str_name == 'cat':        
        return True
func()

lkj


## Question 2

** Create a function that counts the number of times the word "cat" occurs in a string. Again ignore edge cases.  (count CAT, cat, Cat, ....regarless of the case) 

-  Hint : Use split function

In [25]:
str_name = str(input())
str_name = str_name.lower()

def func():
    cnt = str_name.count('cat')
    print(cnt)
func()

catlkjncatlkjdsncat
3


## Question 3

*You are driving a little too fast, and a police officer stops you. Write a function to return one of 3 possible results: "Happy ending", "Not so happy ending!", or "Sad story". If your speed is 65 or less, the result is "Happy ending". If speed is between 66 and 75 inclusive, the result is "Not so happy ending!". If speed is 76 or more, the result is "Sad story". Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, your speed can be 5 higher in all cases. *


In [16]:
import datetime

date = datetime.datetime.now()

month = date.strftime("%m")
day = date.strftime("%d")
today_date = (month + '/' + day)

speed = 0
birthday = str(input('Enter birthday as MM/DD'))

def func():
    speed = int(input('What is your speed?'))
    while birthday == today_date:
        speed = speed - 5
        break
    if speed <= 65:
        print('Happy ending')
    elif speed >= 66 and speed <= 75:
        if birthday == today_date:
            speed = speed - 5
        print('Not so happy ending!')
    elif speed >= 76:
        if birthday == today_date:
            speed = speed - 5
        print('Sad story')
        
print(speed)
    
func()

Enter birthday as MM/DD12/19
0
What is your speed?77
Sad story


## Question 4

### BMI Calculator
1. Accept the height in meters from input  --"What is the height in meters?"
2. Accept the weight in kilograms from input  --"What is the weight in kilograms?"
3. Write a function that includes the below functionality
	1. Takes height and weight as arguments. --BMI = (weight) / (height**2)
	2. The function should implement BMI calculation. 
	3. Should return BMI value
    
4. Based on this value, write if statements to classify a person is obese, overweight, normal, or underweight.
    - Underweight = <18.5
    - Normal weight = 18.5–24.9
    - Overweight = 25–29.9 
    - Obesity = BMI of 30 or greater
    
5. End of the function the BMICalculator(weight_input, height_input) function should be called to complete the task!

In [24]:
weight = float(input('What is the weight in kilograms?'))
height = float(input('What is the height in meters?'))

def bmi_calculator(weight_input, height_input):
    bmi = weight_input/height_input
    if bmi <= 18.5:
        print('underweight')
    elif bmi <= 24.9:
        print('normal weight')
    elif bmi <= 29.9:
        print('overweight')
    elif bmi >= 30:
        print('obesity')
    return bmi
    
bmi_calculator(weight, height)

What is the weight in kilograms?30
What is the height in meters?2
underweight


15.0

## Question 5

Factorial of any number n is represented by n! and is equal to 1 * 2 * 3 * .... * (n-1) * n.
- For example:
 - 4! = 1 * 2 * 3 * 4 = 24
 - 3! = 3 * 2 * 1 = 6
 - 2! = 2 * 1 = 2
  - Also,
       - 1! = 1
       - 0! = 1
       
**Write a program that asks a number input from a user and calculate factorial of that number.**

In [42]:
number = int(input())

def fact(num):
    return 1 if (num == 0) else num * fact(num - 1)

fact(number)

1


1

##  Question 6:  
#### Generate a 3 by 4 matrix that consists of random numbers sampled from a standard normal distribution

In [45]:
import numpy as np

array = np.random.randn(3,4)

print(array)

[[ 0.64103346 -1.11854306  1.25895191 -0.94799169]
 [ 1.42116685 -0.46213466 -0.81575569 -0.06751413]
 [-2.140905   -1.38348905  0.34165114  0.7990374 ]]


## Question 7:  
####  Write the appropriate code in the cell below to create the following matrix:

In [61]:
array = np.arange(.1,2.1,.1)
array = array.reshape(4,5)
print(array)

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8
 1.9 2. ]
[[0.1 0.2 0.3 0.4 0.5]
 [0.6 0.7 0.8 0.9 1. ]
 [1.1 1.2 1.3 1.4 1.5]
 [1.6 1.7 1.8 1.9 2. ]]


## For questions 8, 9 and 10, use the "my_array_1" array that is created in the cell below.

In [74]:
np.random.seed(123)
my_array_1 = np.random.randint(1,16,15).reshape(3,5)
my_array_1

array([[15, 14, 15,  3, 13],
       [ 3,  7,  2,  4, 11],
       [12, 10,  7,  2,  1]])

## Question 8 :

#### Write the code (indexing/slicing) below that generates the new matrix below it.

array([[ 2,  4, 11],
       [ 7,  2,  1]])

In [86]:
one = int(my_array_1[2,3])
two = int(my_array_1[1,3])
three = int(my_array_1[1,4])
four = int(my_array_1[1,1])
five = int(my_array_1[1,2])
six = int(my_array_1[2,4])

new_array = np.array([[one, two, three],[four, five, six]])
print(new_array)

[[ 2  4 11]
 [ 7  2  1]]


## Question 9 :

#### Write the code (indexing/slicing) below that generates the new matrix below it.

array([[14, 15],
       [ 7,  2]])

In [87]:
one = int(my_array_1[0,1])
two = int(my_array_1[0,0])
three = int(my_array_1[1,1])
four = int(my_array_1[1,2])

new_array = np.array([[one, two],[three, four]])
print(new_array)

[[14 15]
 [ 7  2]]


## Question 10 : (Please use "my_array_1" to work on the following steps.

#### Step 1:  Get the sum of all the values in my_array_1
#### Step 2:  Get the standard deviation of the values in my_array_1
#### Step 3:  Get the sum of all the columns in my_array_1


In [89]:
arr_sum = np.sum(my_array_1)
print(arr_sum)

arr_sd = np.std(my_array_1)
print(arr_sd)

#isn't the sum of all the columns the same as the sum of all the values?
arr_sum_col = np.sum(my_array_1, axis=0)
print(arr_sum_col)

119
5.012872319228657
[30 31 24  9 25]


## Good Luck